research_task:
  description: >
    Conduct thorough research about Insurance Technology across the websites provided. Do not hallucinate or fabricate any information.
    
    - Insurtech Insights (https://www.insurtechinsights.com/news-insights/artificial-intelligence/) & make sure research is done by the Insurtech Insights Reporter.
    - InsurTech News (https://insurtechnews.com/) & make sure research is done by the InsurTech News reporter.
    - InsurTech Digital (https://insurtechdigital.com/) & make sure research is done by the InsurTech Digital.

    Priotize relevant information given the current date is { current_date }.
  expected_output: >
    5 Bulletpoints representing the most relevant developments retrieved from the various news outlets. Include a summary of 
    each development and include detailed sources, links and citations so that the information can be verified.